configuration:
  width: 450
  height: 450
  luminosity-label: '%1$.1f fb^{-1} at #sqrt{s} = 13 TeV'
  experiment: " CMS"
  extra-label: "Preliminary"
  root: ''
  luminosity: 101270 #17 + 18
  luminosity-error: 0.024 #0.23 + 0.25 / 2
  error-fill-style: 3154
  error-fill-color: "#ee556270"
  staterror-fill-style: 3145
  staterror-fill-color: 7
  ratio-fit-error-fill-style: 1001
  ratio-fit-error-fill-color: "#aa556270"
  ratio-fit-line-color: "#0B486B"
  blinded-range-fill-color: "#29556270"
  blinded-range-fill-style: 1001
  yields-table-align: v
  book-keeping-file: 'plots.root'
  yields-table-numerical-precision-yields: 2

files: 
  include: ['files_1718.yml']

legend:
  position: [0.18, 0.70, 0.96, 0.88]
  #position: [0.18, 0.80, 0.96, 0.92]
  columns: 5

groups:
  include: ['groups.yml']

